const BIRDS = [
  { id: '1', name: 'Tūī', scientific: 'Prosthemadera novaeseelandiae', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/95/Tui_Birdlife_Photography.jpg/320px-Tui_Birdlife_Photography.jpg' },
  { id: '2', name: 'Kiwi (North Island Brown)', scientific: 'Apteryx mantelli', emoji: '🥝',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8a/Apteryx_mantelli_-Wairakei_-New_Zealand-8.jpg/320px-Apteryx_mantelli_-Wairakei_-New_Zealand-8.jpg' },
  { id: '3', name: 'Kea', scientific: 'Nestor notabilis', emoji: '🦜',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8d/Kea_in_flight.jpg/320px-Kea_in_flight.jpg' },
  { id: '4', name: 'Kererū', scientific: 'Hemiphaga novaeseelandiae', emoji: '🕊️',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/c/c0/Hemiphaga_novaeseelandiae_-_Karori_Wildlife_Sanctuary.jpg/320px-Hemiphaga_novaeseelandiae_-_Karori_Wildlife_Sanctuary.jpg' },
  { id: '5', name: 'Pīwakawaka (Fantail)', scientific: 'Rhipidura fuliginosa', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/52/Fantail_on_branch.jpg/320px-Fantail_on_branch.jpg' },
  { id: '6', name: 'Pūkeko', scientific: 'Porphyrio melanotus', emoji: '🦚',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e5/Porphyrio_melanotus_-Christchurch-8.jpg/320px-Porphyrio_melanotus_-Christchurch-8.jpg' },
  { id: '7', name: 'Korimako (Bellbird)', scientific: 'Anthornis melanura', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/15/Anthornis_melanura_-Tiritiri_Matangi_Island-8.jpg/320px-Anthornis_melanura_-Tiritiri_Matangi_Island-8.jpg' },
  { id: '8', name: 'Kākā', scientific: 'Nestor meridionalis', emoji: '🦜',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4a/Nestor_meridionalis_-Karori_Wildlife_Sanctuary-8.jpg/320px-Nestor_meridionalis_-Karori_Wildlife_Sanctuary-8.jpg' },
  { id: '9', name: 'Kōkako', scientific: 'Callaeas wilsoni', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Kokako_-_Tiritiri_Matangi.jpg/320px-Kokako_-_Tiritiri_Matangi.jpg' },
  { id: '10', name: 'Takahē', scientific: 'Porphyrio hochstetteri', emoji: '🦤',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Takahe_Notornis_mantelli.jpg/320px-Takahe_Notornis_mantelli.jpg' },
  { id: '11', name: 'Kākāpō', scientific: 'Strigops habroptilus', emoji: '🦜',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/8/8c/Kakapo_Sirocco.jpg/320px-Kakapo_Sirocco.jpg' },
  { id: '12', name: 'Ruru (Morepork)', scientific: 'Ninox novaeseelandiae', emoji: '🦉',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/1e/Morepork_-_Ruru_%28Ninox_novaeseelandiae%29.jpg/320px-Morepork_-_Ruru_%28Ninox_novaeseelandiae%29.jpg' },
  { id: '13', name: 'Kārearea (NZ Falcon)', scientific: 'Falco novaeseelandiae', emoji: '🦅',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e0/Falco_novaeseelandiae_-Wingspan_Birds_of_Prey_Trust-8.jpg/320px-Falco_novaeseelandiae_-Wingspan_Birds_of_Prey_Trust-8.jpg' },
  { id: '14', name: 'Weka', scientific: 'Gallirallus australis', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b7/Weka_Gallirallus_australis.jpg/320px-Weka_Gallirallus_australis.jpg' },
  { id: '15', name: 'Kōtare (Kingfisher)', scientific: 'Todiramphus sanctus', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/19/Sacred_Kingfisher_-_Todiramphus_sanctus.jpg/320px-Sacred_Kingfisher_-_Todiramphus_sanctus.jpg' },
  { id: '16', name: 'Tīeke (Saddleback)', scientific: 'Philesturnus rufusater', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/North_Island_saddleback.jpg/320px-North_Island_saddleback.jpg' },
  { id: '17', name: 'Hihi (Stitchbird)', scientific: 'Notiomystis cincta', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/1/16/Stitchbird_-_Hihi_male.jpg/320px-Stitchbird_-_Hihi_male.jpg' },
  { id: '18', name: 'Tauhou (Silvereye)', scientific: 'Zosterops lateralis', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/7/79/Silvereye_Dec_2008.jpg/320px-Silvereye_Dec_2008.jpg' },
  { id: '19', name: 'Kōtuku (White Heron)', scientific: 'Ardea alba modesta', emoji: '🦢',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/9/9f/Ardea_alba_-Bundaberg%2C_Queensland%2C_Australia-8.jpg/320px-Ardea_alba_-Bundaberg%2C_Queensland%2C_Australia-8.jpg' },
  { id: '20', name: 'Tākapu (Gannet)', scientific: 'Morus serrator', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/56/Australasian_Gannet_Dec_2008.jpg/320px-Australasian_Gannet_Dec_2008.jpg' },
  { id: '21', name: 'Tōrea (Oystercatcher)', scientific: 'Haematopus ostralegus', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/0/00/Haematopus_ostralegus_-Texel-8.jpg/320px-Haematopus_ostralegus_-Texel-8.jpg' },
  { id: '22', name: 'Paradise Shelduck', scientific: 'Tadorna variegata', emoji: '🦆',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/b/b4/Tadorna_variegata_-_Te_Anau.jpg/320px-Tadorna_variegata_-_Te_Anau.jpg' },
  { id: '23', name: 'NZ Robin (Toutouwai)', scientific: 'Petroica longipes', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/54/North_Island_Robin.jpg/320px-North_Island_Robin.jpg' },
  { id: '24', name: 'Mohua (Yellowhead)', scientific: 'Mohoua ochrocephala', emoji: '🐦',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e1/Yellowhead_Mohua_ochrocephala.jpg/320px-Yellowhead_Mohua_ochrocephala.jpg' },
  { id: '25', name: 'Swamp Harrier (Kāhu)', scientific: 'Circus approximans', emoji: '🦅',
    image: 'https://upload.wikimedia.org/wikipedia/commons/thumb/4/4e/Swamp_Harrier_Dec_2008.jpg/320px-Swamp_Harrier_Dec_2008.jpg' },
];

export default BIRDS;
